// PRIMUS HOME PRO - Temporary Type Declarations for Module K
// These types will be auto-generated by Prisma once schema is migrated
// DELETE THIS FILE after running: npx prisma generate

// UserRole enum (matches schema)
export type UserRole = 'ADMIN' | 'SALES' | 'SCHEDULER' | 'INSTALLER';

// Export for use in components before Prisma client is regenerated
export const UserRoleValues = {
  ADMIN: 'ADMIN' as const,
  SALES: 'SALES' as const,
  SCHEDULER: 'SCHEDULER' as const,
  INSTALLER: 'INSTALLER' as const,
};
